version: "3"

services:
  app:
    build:
      context: . 
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      FLASK_APP: server.py
      FLASK_ENV: development
    networks:
      - default

networks:
    default: # this network (app2)
        driver: bridge
    app1_default: # external network (app1)
        external: true